"use strict";
const el=id=>document.getElementById(id), canvas=el('capture-canvas'),ctx=canvas.getContext('2d');
const colours=['#217955','#b34852','#356ca0','#9766a4'];
let library,run,index=0,playing=false,last=0,elapsed=0,requestId=0,bounds;
async function get(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
function path(points,colour,fill=false){if(!points.length)return;ctx.beginPath();points.forEach((p,i)=>{const q=screen(p);i?ctx.lineTo(...q):ctx.moveTo(...q);});if(fill){ctx.closePath();ctx.fillStyle=colour;ctx.fill();}else{ctx.strokeStyle=colour;ctx.lineWidth=1.6;ctx.stroke();}}
function screen(p){const w=canvas.clientWidth,h=canvas.clientHeight,scale=Math.min((w-60)/(bounds[2]-bounds[0]),(h-60)/(bounds[3]-bounds[1]));return [w/2+(p[0]-(bounds[0]+bounds[2])/2)*scale,h/2-(p[1]-(bounds[1]+bounds[3])/2)*scale];}
function cross(p,colour){if(!p)return;const [x,y]=screen(p);ctx.strokeStyle=colour;ctx.beginPath();ctx.moveTo(x-4,y);ctx.lineTo(x+4,y);ctx.moveTo(x,y-4);ctx.lineTo(x,y+4);ctx.stroke();}
function draw(){if(!run)return;const dpr=devicePixelRatio||1;canvas.width=canvas.clientWidth*dpr;canvas.height=canvas.clientHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#f4f7f6';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);
 if(el('work').checked)for(let i=0;i<=index;i++)for(const m of run.frames[i].machines){if(m.state.lowered!==true)continue;for(const poly of m.work)path(poly,'#b9d9c5',true);}
 if(el('traces').checked)for(const [j,member]of run.summary.members.entries())path(run.frames.slice(0,index+1).map(f=>f.machines.find(m=>m.instance===member.instance).position),colours[j%colours.length]);
 const frame=run.frames[index];for(const [j,m]of frame.machines.entries()){const c=colours[j%colours.length];if(m.body.length)path([...m.body,m.body[0]],c);cross(m.position,c);cross(m.axle,'#222');cross(m.hitch,'#df981d');if(m.hitch&&m.axle)path([m.hitch,m.axle],c);for(const poly of m.work)path([...poly,poly[0]],c);const [x,y]=screen(m.position);ctx.fillStyle=c;ctx.font='12px system-ui';ctx.fillText(String(m.instance),x+7,y-7);}
 el('time').value=index;el('clock').textContent=`${frame.time.toFixed(1)} / ${run.summary.duration.toFixed(1)} s`;el('play').textContent=playing?'Pause':'Play';
}
async function load(){const id=++requestId;playing=false;el('status').textContent='Loading capture…';try{const data=await get('/api/captures/'+el('recording').value);if(id!==requestId)return;run=data;index=0;elapsed=run.frames[0].time;el('time').max=run.frames.length-1;bounds=[Infinity,Infinity,-Infinity,-Infinity];for(const f of run.frames)for(const m of f.machines)for(const p of [m.position,...m.body,...m.work.flat()]){bounds[0]=Math.min(bounds[0],p[0]);bounds[1]=Math.min(bounds[1],p[1]);bounds[2]=Math.max(bounds[2],p[0]);bounds[3]=Math.max(bounds[3],p[1]);}bounds[2]=Math.max(bounds[0]+1,bounds[2]);bounds[3]=Math.max(bounds[1]+1,bounds[3]);
 el('summary').textContent=`${run.summary.samples} samples · ${run.summary.duration.toFixed(1)} seconds · Saved on ${run.summary.stopReason}`;
 el('machines').replaceChildren();run.summary.members.forEach((m,i)=>{const profile=library.machines.find(p=>p.source===m.profileFile).geometry,a=document.createElement('article');a.style.setProperty('--colour',colours[i%colours.length]);const title=document.createElement('b');title.textContent=`${m.instance}. ${m.identity.name}`;a.append(title);for(const text of [`Parent: ${m.parentInstance??'tractor'} · Working width: ${Number((run.summary.widths[i]||0).toFixed(2))||'—'} m`,Object.entries(profile.labels||{}).filter(([,v])=>v!=='unspecified').map(([k,v])=>`${k}: ${v}`).join(' · ')||'Optional labels not supplied',`Lowered samples: ${run.summary.loweredSamples[m.instance]} · Lift/lower changes: ${run.summary.loweringTransitions[m.instance]}`]){const p=document.createElement('p');p.textContent=text;a.append(p);}el('machines').append(a);});
 el('status').textContent='Recorded geometry loaded. This view does not predict a new turn.';draw();}catch(e){el('status').textContent=e.message;}}
el('recording').onchange=load;el('traces').onchange=draw;el('work').onchange=draw;
el('time').oninput=()=>{playing=false;index=+el('time').value;elapsed=run.frames[index].time;draw();};
el('restart').onclick=()=>{if(!run)return;playing=false;index=0;elapsed=run.frames[0].time;draw();};
el('play').onclick=()=>{if(!run)return;if(index===run.frames.length-1){index=0;elapsed=run.frames[0].time;}playing=!playing;draw();};
function tick(now){if(playing&&run){elapsed+=(now-last)/1000*Number(el('speed').value);while(index<run.frames.length-1&&run.frames[index+1].time<=elapsed)index++;if(index===run.frames.length-1)playing=false;draw();}last=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);new ResizeObserver(draw).observe(canvas);
get('/api/captures').then(data=>{library=data;for(const r of data.recordings){const o=document.createElement('option');o.value=r.id;o.textContent=r.title+' · '+r.source.match(/_(\d{6})_\d+\.jsonl$/)[1];el('recording').append(o);}return load();}).catch(e=>el('status').textContent=e.message);
